"""empty message

Revision ID: 00d7a7ab1e86
Revises: d30425f1ce9f
Create Date: 2017-08-21 23:47:38.416927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00d7a7ab1e86'
down_revision = 'd30425f1ce9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clothing_color_ratio_ibfk_3', 'clothing_color_ratio', type_='foreignkey')
    op.drop_column('clothing_color_ratio', 'rule_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_color_ratio', sa.Column('rule_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('clothing_color_ratio_ibfk_3', 'clothing_color_ratio', 'fashion_rule', ['rule_id'], ['id'])
    # ### end Alembic commands ###
