"""empty message

Revision ID: 0c21e56521e9
Revises: 00d7a7ab1e86
Create Date: 2017-08-21 23:48:39.977512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c21e56521e9'
down_revision = '00d7a7ab1e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clothing_color_ratio_ibfk_1', 'clothing_color_ratio', type_='foreignkey')
    op.drop_constraint('clothing_color_ratio_ibfk_2', 'clothing_color_ratio', type_='foreignkey')
    op.drop_column('clothing_color_ratio', 'category_id')
    op.drop_column('clothing_color_ratio', 'color_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_color_ratio', sa.Column('color_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('clothing_color_ratio', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('clothing_color_ratio_ibfk_2', 'clothing_color_ratio', 'color', ['color_id'], ['id'])
    op.create_foreign_key('clothing_color_ratio_ibfk_1', 'clothing_color_ratio', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
