"""empty message

Revision ID: 11396c9e145d
Revises: 0c21e56521e9
Create Date: 2017-08-21 23:48:58.035239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11396c9e145d'
down_revision = '0c21e56521e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_color_ratio', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('clothing_color_ratio', sa.Column('color_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clothing_color_ratio', 'color', ['color_id'], ['id'])
    op.create_foreign_key(None, 'clothing_color_ratio', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clothing_color_ratio', type_='foreignkey')
    op.drop_constraint(None, 'clothing_color_ratio', type_='foreignkey')
    op.drop_column('clothing_color_ratio', 'color_id')
    op.drop_column('clothing_color_ratio', 'category_id')
    # ### end Alembic commands ###
