"""empty message

Revision ID: 1b35cf6ee866
Revises: 
Create Date: 2017-04-06 18:26:56.494811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b35cf6ee866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=False),
    sa.Column('is_childish', sa.Boolean(), nullable=True),
    sa.Column('lamoda_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lamoda_url')
    )
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hex', sa.String(length=32), nullable=True),
    sa.Column('rgb', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('site_url', sa.String(length=128), nullable=False),
    sa.Column('logo_url', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('site_url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.Column('uv_card', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(length=1024), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=False),
    sa.Column('is_childish', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('height', sa.SmallInteger(), nullable=True),
    sa.Column('inner_seam_length', sa.SmallInteger(), nullable=True),
    sa.Column('along_side_seam_length', sa.SmallInteger(), nullable=True),
    sa.Column('circumference_at_waist', sa.SmallInteger(), nullable=True),
    sa.Column('circumference_at_hips', sa.SmallInteger(), nullable=True),
    sa.Column('bottom_width', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('colors',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colors')
    op.drop_table('product')
    op.drop_table('user')
    op.drop_table('source')
    op.drop_table('color')
    op.drop_table('category')
    # ### end Alembic commands ###
