"""empty message

Revision ID: 1d8b48c5ec37
Revises: 11396c9e145d
Create Date: 2017-08-21 23:56:00.566586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d8b48c5ec37'
down_revision = '11396c9e145d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clothing_color_ratio', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('clothing_color_ratio', 'color_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('fashion_rule', 'season_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fashion_rule', 'season_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('clothing_color_ratio', 'color_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('clothing_color_ratio', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
