"""empty message

Revision ID: 217458d1c4df
Revises: 1b35cf6ee866
Create Date: 2017-04-18 18:41:53.600787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217458d1c4df'
down_revision = '1b35cf6ee866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chest_girth', sa.Float(), nullable=True),
    sa.Column('waist_girth', sa.Float(), nullable=False),
    sa.Column('hip_girth', sa.Float(), nullable=False),
    sa.Column('sleeve_length', sa.String(32), nullable=True),
    sa.Column('russia', sa.SmallInteger(), nullable=False),
    sa.Column('europe', sa.SmallInteger(), nullable=True),
    sa.Column('uk', sa.SmallInteger(), nullable=True),
    sa.Column('usa', sa.SmallInteger(), nullable=True),
    sa.Column('international', sa.String(32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('length', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'length')
    op.drop_table('size')
    # ### end Alembic commands ###
