"""empty message

Revision ID: 3a16f81ae2e6
Revises: ac23f408351b
Create Date: 2017-04-04 01:30:06.550094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a16f81ae2e6'
down_revision = 'ac23f408351b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'parent_id')
    # ### end Alembic commands ###
