"""empty message

Revision ID: 4a0f3f1d69cf
Revises: cf4830d92d07
Create Date: 2017-04-19 15:11:55.140608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a0f3f1d69cf'
down_revision = 'cf4830d92d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('hip_girth', sa.SmallInteger(), nullable=True))
    op.add_column('product', sa.Column('sleeve_length', sa.SmallInteger(), nullable=True))
    op.add_column('product', sa.Column('waist_girth', sa.SmallInteger(), nullable=True))
    op.drop_column('product', 'circumference_at_waist')
    op.drop_column('product', 'circumference_at_hips')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('circumference_at_hips', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('circumference_at_waist', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('product', 'waist_girth')
    op.drop_column('product', 'sleeve_length')
    op.drop_column('product', 'hip_girth')
    # ### end Alembic commands ###
