"""empty message

Revision ID: 4d3654393b8d
Revises: 2c5ad2c1554f
Create Date: 2017-04-04 14:19:22.904108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d3654393b8d'
down_revision = '2c5ad2c1554f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('color', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('color', 'rgb',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('color', 'rgb',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('color', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
