"""empty message

Revision ID: 647f0f080d6e
Revises: e65d90d5e42b
Create Date: 2017-04-02 14:49:14.771982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647f0f080d6e'
down_revision = 'e65d90d5e42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
