"""empty message

Revision ID: 660c8f8c15cd
Revises: e7cfded62412
Create Date: 2017-04-04 00:15:36.288897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660c8f8c15cd'
down_revision = 'e7cfded62412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('gender', sa.String(length=64), nullable=False))
    op.add_column('category', sa.Column('is_childish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_childish')
    op.drop_column('category', 'gender')
    # ### end Alembic commands ###
