"""empty message

Revision ID: 67d815e2edc0
Revises: b4e4bc98a182
Create Date: 2017-04-04 01:16:49.001916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d815e2edc0'
down_revision = 'b4e4bc98a182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('lamoda_url', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'category', ['lamoda_url'])
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_ibfk_1', 'category', 'category', ['parent_id'], ['id'])
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'lamoda_url')
    # ### end Alembic commands ###
