"""empty message

Revision ID: 6f0549e2f7cb
Revises: 3274c0bcc86d
Create Date: 2017-04-20 01:16:06.557161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0549e2f7cb'
down_revision = '3274c0bcc86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_size', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint('US_category_id_size_id', 'category_size', ['category_id', 'size_id'])
    op.add_column('product_color', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint('US_product_id_color_id', 'product_color', ['product_id', 'color_id'])
    op.add_column('product_size', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint('US_product_id_size_id', 'product_size', ['product_id', 'size_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('US_product_id_size_id', 'product_size', type_='unique')
    op.drop_column('product_size', 'id')
    op.drop_constraint('US_product_id_color_id', 'product_color', type_='unique')
    op.drop_column('product_color', 'id')
    op.drop_constraint('US_category_id_size_id', 'category_size', type_='unique')
    op.drop_column('category_size', 'id')
    # ### end Alembic commands ###
