"""empty message

Revision ID: aae8bf8b6561
Revises: 6f0549e2f7cb
Create Date: 2017-04-20 01:25:48.170639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aae8bf8b6561'
down_revision = '6f0549e2f7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_size', 'id')
    op.drop_column('product_color', 'id')
    op.drop_column('product_size', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_size', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('product_color', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('category_size', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
