"""empty message

Revision ID: ac23f408351b
Revises: eb5abdfec32a
Create Date: 2017-04-04 01:29:42.740580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac23f408351b'
down_revision = 'eb5abdfec32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.drop_column('category', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('category_ibfk_1', 'category', 'category', ['parent_id'], ['id'])
    # ### end Alembic commands ###
