"""empty message

Revision ID: b4e4bc98a182
Revises: 660c8f8c15cd
Create Date: 2017-04-04 01:15:34.354049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4e4bc98a182'
down_revision = '660c8f8c15cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'lamoda_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('lamoda_url', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
