"""empty message

Revision ID: d0af47327be5
Revises: 647f0f080d6e
Create Date: 2017-04-02 15:38:56.951326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0af47327be5'
down_revision = '647f0f080d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('uv_card', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'uv_card')
    # ### end Alembic commands ###
