"""empty message

Revision ID: d30425f1ce9f
Revises: 
Create Date: 2017-08-21 23:39:21.024390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd30425f1ce9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_clothing_color_ratio',
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('color_ratio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_ratio_id'], ['clothing_color_ratio.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['fashion_rule.id'], ),
    sa.UniqueConstraint('rule_id', 'color_ratio_id', name='US_rule_id_color_ratio_id')
    )
    op.drop_column('category_size', 'id')
    op.drop_column('product_color', 'id')
    op.drop_column('product_size', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_size', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('product_color', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('category_size', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('rule_clothing_color_ratio')
    # ### end Alembic commands ###
