"""empty message

Revision ID: e7cfded62412
Revises: d0af47327be5
Create Date: 2017-04-03 23:33:30.316292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7cfded62412'
down_revision = 'd0af47327be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_column('category', 'gender')
    op.drop_column('category', 'is_childish')
    op.add_column('good', sa.Column('gender', sa.String(length=64), nullable=False))
    op.add_column('good', sa.Column('is_childish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'is_childish')
    op.drop_column('good', 'gender')
    op.add_column('category', sa.Column('is_childish', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('gender', mysql.VARCHAR(length=64), nullable=False))
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('login', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
