"""empty message

Revision ID: eb5abdfec32a
Revises: 67d815e2edc0
Create Date: 2017-04-04 01:17:08.311953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5abdfec32a'
down_revision = '67d815e2edc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_ibfk_1', 'category', 'category', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
